# Script by Anuke
name: Tests
on:
  push:
    paths:
      - 'bundles/bundle.properties'
  workflow_dispatch:

jobs:
  runPush:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update bundles
        run: |
          ./gradlew updateBundles
          
          git add bundles/
          
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "Auto bundle update"
            git push
          else
            echo "No diff ig."
          fi
